name: unimarky
description: "UniMARKY â€” Your Campus Hub"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter

  # Auth & Backend
  supabase_flutter: ^2.8.4
  dio: ^5.8.0+1

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Routing
  go_router: ^14.8.1

  flutter_svg: ^2.0.14

  # UI & Icons
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  flutter_animate: ^4.5.2

  # Image Handling
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0

  # Storage & Utils
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  url_launcher: ^6.3.1
  path_provider: ^2.1.5
  intl: ^0.19.0
  open_file: ^3.5.10

  # Toast / Snackbar
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  riverpod_generator: ^2.6.3
  build_runner: ^2.4.14

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
